import { MappingCategory } from "~/utils/types/MappingCategory";

export type Language =
  | "ab"
  | "aa"
  | "af"
  | "ak"
  | "sq"
  | "am"
  | "ar"
  | "an"
  | "hy"
  | "as"
  | "av"
  | "ae"
  | "ay"
  | "az"
  | "bm"
  | "ba"
  | "eu"
  | "be"
  | "bn"
  | "bi"
  | "bs"
  | "br"
  | "bg"
  | "my"
  | "ca"
  | "ch"
  | "ce"
  | "ny"
  | "zh"
  | "cv"
  | "kw"
  | "co"
  | "cr"
  | "hr"
  | "cs"
  | "da"
  | "dv"
  | "nl"
  | "dz"
  | "en"
  | "eo"
  | "et"
  | "ee"
  | "fo"
  | "fj"
  | "fi"
  | "fr"
  | "ff"
  | "gl"
  | "ka"
  | "de"
  | "el"
  | "gn"
  | "gu"
  | "ht"
  | "ha"
  | "he"
  | "hz"
  | "hi"
  | "ho"
  | "hu"
  | "ia"
  | "id"
  | "ie"
  | "ga"
  | "ig"
  | "ik"
  | "io"
  | "is"
  | "it"
  | "iu"
  | "ja"
  | "jv"
  | "kl"
  | "kn"
  | "kr"
  | "ks"
  | "kk"
  | "km"
  | "ki"
  | "rw"
  | "ky"
  | "kv"
  | "kg"
  | "ko"
  | "ku"
  | "kj"
  | "la"
  | "lb"
  | "lg"
  | "li"
  | "ln"
  | "lo"
  | "lt"
  | "lu"
  | "lv"
  | "gv"
  | "mk"
  | "mg"
  | "ms"
  | "ml"
  | "mt"
  | "mi"
  | "mr"
  | "mh"
  | "mn"
  | "na"
  | "nv"
  | "nd"
  | "ne"
  | "ng"
  | "nb"
  | "nn"
  | "no"
  | "ii"
  | "nr"
  | "oc"
  | "oj"
  | "cu"
  | "om"
  | "or"
  | "os"
  | "pa"
  | "pi"
  | "fa"
  | "pl"
  | "ps"
  | "pt"
  | "qu"
  | "rm"
  | "rn"
  | "ro"
  | "ru"
  | "sa"
  | "sc"
  | "sd"
  | "se"
  | "sm"
  | "sg"
  | "sr"
  | "gd"
  | "sn"
  | "si"
  | "sk"
  | "sl"
  | "so"
  | "st"
  | "es"
  | "su"
  | "sw"
  | "ss"
  | "sv"
  | "ta"
  | "te"
  | "tg"
  | "th"
  | "ti"
  | "bo"
  | "tk"
  | "tl"
  | "tn"
  | "to"
  | "tr"
  | "ts"
  | "tt"
  | "tw"
  | "ty"
  | "ug"
  | "uk"
  | "ur"
  | "uz"
  | "ve"
  | "vi"
  | "vo"
  | "wa"
  | "cy"
  | "wo"
  | "fy"
  | "xh"
  | "yi"
  | "yo"
  | "za"
  | "zu";
export type Identifier =
  | "DOI"
  | "ARK"
  | "ROR"
  | "ORCID"
  | "IGSN"
  | "ISNI"
  | "GRID"
  | "Crossref FunderID"
  | "handle"
  | "re3data ID"
  | "arXiv"
  | "bibcode"
  | "EAN13"
  | "EISSN"
  | "ISBN"
  | "ISTC"
  | "LISSN"
  | "LSID"
  | "PMID"
  | "PURL"
  | "UPC"
  | "URL"
  | "URN"
  | "w3id"
  | "MSC ID (Bath version)"
  | "SPDX"
  | "Trove"
  | "DEP5"
  | "other";
export type ContactIdentifier =
  | "ORCID"
  | "VIAF"
  | "GND"
  | "ISNI"
  | "OpenID"
  | "ResearcherID"
  | "ROR"
  | "other";
export type HelmholtzResearchArea =
  | "Aeronautics, Space and Transport"
  | "Earth and Environment"
  | "Energy"
  | "Health"
  | "Information"
  | "Matter";
export type HelmholtzCenter =
  | "AWI"
  | "CISPA"
  | "DESY"
  | "DKFZ"
  | "DLR"
  | "DZNE"
  | "FZJ"
  | "GEOMAR"
  | "GFZ"
  | "GSI"
  | "Hereon"
  | "HMGU"
  | "HZB"
  | "HZDR"
  | "HZI"
  | "KIT"
  | "MDC"
  | "UFZ";
export type NameType =
  | "name"
  | "abbreviation"
  | "alternative name"
  | "translated name"
  | "other";
export type ContactRole =
  | "contact person"
  | "data manager"
  | "distributor"
  | "editor"
  | "hosting institution"
  | "producer"
  | "project leader"
  | "project manager"
  | "project member"
  | "registration agency"
  | "registration authority"
  | "related person"
  | "researcher"
  | "research group"
  | "rights holder"
  | "other";
export type RelationType =
  | "describes"
  | "is version of"
  | "is part of"
  | "is identical to"
  | "requires"
  | "is required by"
  | "relation"
  | "conforms to"
  | "replaces"
  | "uses"
  | "recommends"
  | "supports"
  | "provides"
  | "maintained by"
  | "manufatured by"
  | "issued by"
  | "published by";
export type ScientificDiscipline =
  | "Subject Agnostic"
  | "Chemistry"
  | "Chemistry: Analytical Chemistry"
  | "Chemistry: Biochemistry"
  | "Chemistry: Biomimetic Chemistry"
  | "Chemistry: Chemical Engineering"
  | "Chemistry: Cheminformatics"
  | "Chemistry: Drug Discovery"
  | "Chemistry: Food Chemistry"
  | "Chemistry: Geochemistry"
  | "Chemistry: Molecular Chemistry"
  | "Chemistry: Organic Chemistry"
  | "Chemistry: Physical Chemistry"
  | "Chemistry: Polymer Research"
  | "Chemistry: Synthetic Chemistry"
  | "Chemistry: Technical Chemistry"
  | "Chemistry: Theoretical Chemistry"
  | "Earth Science"
  | "Earth Science: Atmospheric Science"
  | "Earth Science: Environmental Science"
  | "Earth Science: Geography"
  | "Earth Science: Geology"
  | "Earth Science: Geophysics"
  | "Earth Science: Oceanography"
  | "Earth Science: Paleontology"
  | "Earth Science: Soil Science"
  | "Earth Science: Water Research"
  | "Life Science"
  | "Life Science: Agriculture"
  | "Life Science: Biology"
  | "Life Science: Fisheries Science"
  | "Life Science: Health Science"
  | "Life Science: Medicine"
  | "Life Science: Natural History"
  | "Mathematics"
  | "Mathematics: Applied Mathematics"
  | "Mathematics: Mathematical Psychology"
  | "Mathematics: Nonlinear Dynamics"
  | "Mathematics: Population Dynamics"
  | "Mathematics: Pure Mathematics"
  | "Mathematics: Statistics"
  | "Physics"
  | "Physics: Acoustics"
  | "Physics: Astrophysics and Astronomy"
  | "Physics: Atomic, Molecular, Optical and Plasma Physics"
  | "Physics: Biophysics"
  | "Physics: Building Engineering Physics"
  | "Physics: Computational Neuroscience"
  | "Physics: Condensed Matter Physics"
  | "Physics: Mechanics"
  | "Physics: Meteorology"
  | "Physics: Nanotechnology"
  | "Physics: Nonlinear Dynamics"
  | "Physics: Particles, Nuclei and Fields"
  | "Physics: Polymer Physics"
  | "Physics: Soft Matter Physics"
  | "Physics: Statistical Physics"
  | "Physics: Thermodynamics"
  | "Engineering Science"
  | "Engineering Science: Aerospace Engineering"
  | "Engineering Science: Bioengineering"
  | "Engineering Science: Civil Engineering"
  | "Engineering Science: Computer Science"
  | "Engineering Science: Electrical Engineering"
  | "Engineering Science: Energy Engineering"
  | "Engineering Science: Industrial Engineering"
  | "Engineering Science: Maritime Engineering"
  | "Engineering Science: Materials Engineering"
  | "Engineering Science: Mechanical Engineering"
  | "Engineering Science: Process Engineering"
  | "Engineering Science: Systems Engineering"
  | "Engineering Science: Transportation Engineering";

export interface CommonProperties {
  resourceName: {
    name: string;
    nameType: NameType;
    nameLanguage?: Language;
  }[];
  resourceDescription: string;
  resourceUri?: string[];
  documentationUri?: string[];
  mappingCategory?: MappingCategory;
  identifier?: {
    id: string;
    identifierType: Identifier;
  }[];
  contact?: {
    contactName?: string;
    contactIdentifier?: string;
    contactIdentifierSystem?: ContactIdentifier;
    contactUri?: string;
    contactRole?: ContactRole;
  }[];
  keyword?: string[];
  date?: {
    resourceDate: Date;
    dateType: "start date" | "end date" | "modified";
  }[];
  resourceStatus?: "valid" | "invalid" | "uncertain";
  relatedHelmholtzCentre?: {
    helmholtzCentre: HelmholtzCenter;
    relationType: RelationType;
  }[];
  scientificDiscipline?: ScientificDiscipline;
  helmholtzResearchField?: HelmholtzResearchArea;
}

export interface IPBaseObject extends CommonProperties {
  _id: string;
}
